/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropManagerSol from "./AirdropManager.sol";
export type { airdropManagerSol };
import type * as customAirdrop1155Sol from "./CustomAirdrop1155.sol";
export type { customAirdrop1155Sol };
export type { Administrable } from "./Administrable";
