/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomAirdrop1155__factory } from "./CustomAirdrop1155__factory";
export { IERC1155__factory } from "./IERC1155__factory";
