/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AirdropManager__factory } from "./AirdropManager__factory";
export { IAirdrop1155__factory } from "./IAirdrop1155__factory";
