/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as airdropManagerSol from "./AirdropManager.sol";
export * as customAirdrop1155Sol from "./CustomAirdrop1155.sol";
export { Administrable__factory } from "./Administrable__factory";
