/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Administrable } from "./contracts/Administrable";
export { Administrable__factory } from "./factories/contracts/Administrable__factory";
export type { AirdropManager } from "./contracts/AirdropManager.sol/AirdropManager";
export { AirdropManager__factory } from "./factories/contracts/AirdropManager.sol/AirdropManager__factory";
export type { IAirdrop1155 } from "./contracts/AirdropManager.sol/IAirdrop1155";
export { IAirdrop1155__factory } from "./factories/contracts/AirdropManager.sol/IAirdrop1155__factory";
export type { CustomAirdrop1155 } from "./contracts/CustomAirdrop1155.sol/CustomAirdrop1155";
export { CustomAirdrop1155__factory } from "./factories/contracts/CustomAirdrop1155.sol/CustomAirdrop1155__factory";
export type { IERC1155 } from "./contracts/CustomAirdrop1155.sol/IERC1155";
export { IERC1155__factory } from "./factories/contracts/CustomAirdrop1155.sol/IERC1155__factory";
